on:
  push:
    branches:
      - integ-tests

name: Integration Test

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Print current build ID
      run: |
        echo Integration test run: githubactionsamazonecsdeplo-NWcjHIgDJLXw:622bdd90-e616-4c11-9e51-c98a8149a03f

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsDeployTaskIntegrationTests
        role-session-name: deploy_task_integration_tests
        aws-region: us-west-2

    - name: Deploy Amazon ECS task definition with one-off task and wait for task stopped set to false
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: task-definition-run-task.json
        cluster: github-actions-deploy-task-def-integ-test
        run-task: true
        run-task-subnets: subnet-e5604fce, subnet-fe9355b4, subnet-c49431bc, subnet-392f9b64
        run-task-assign-public-IP: ENABLED
        run-task-security-groups: sg-067ebcde49c0f3ad8
        run-task-launch-type: FARGATE
        wait-for-task-stopped: false 

    - name: Deploy Amazon ECS task definition with one-off task and wait for task stopped set to true
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: task-definition-run-task.json
        cluster: github-actions-deploy-task-def-integ-test
        run-task: true
        run-task-subnets: subnet-e5604fce, subnet-fe9355b4, subnet-c49431bc, subnet-392f9b64
        run-task-assign-public-IP: ENABLED
        run-task-security-groups: sg-067ebcde49c0f3ad8
        run-task-launch-type: FARGATE
        wait-for-task-stopped: true

    - name: Deploy Amazon ECS task definition with ECS Service
      uses: aws-actions/amazon-ecs-deploy-task-definition@f4999fde756bdd5f0c688fc1d827b432cc207d57
      with:
        task-definition: task-definition.json
        service: github-actions-deploy-task-def-integ-test
        cluster: github-actions-deploy-task-def-integ-test
        wait-for-service-stability: true
